/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogodevolei.view;

import java.awt.Button;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import jogodevolei.Model.Equipe;
import jogodevolei.Model.Partida;

/**
 *
 * @author User-OEM
 */
public class Tela extends javax.swing.JFrame {

    Partida partida;
    Equipe a, b;

    public Tela() {
        initComponents();
        tiraBotao(btAddA1, btAddB1, btRmvA1, btRmvB1, btTerminar1);
        tiraBotao(btAddA2, btAddB2, btRmvA2, btRmvB2, btTerminar2);
        tiraBotao(btAddA3, btAddB3, btRmvA3, btRmvB3, btTerminar3);
        tiraBotao(btAddA4, btAddB4, btRmvA4, btRmvB4, btTerminar4);
        tiraBotao(btAddA5, btAddB5, btRmvA5, btRmvB5, btTerminar5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btInicio = new javax.swing.JButton();
        tfEquipeA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbNomeA = new javax.swing.JLabel();
        tfHora = new javax.swing.JTextField();
        lbNomeB = new javax.swing.JLabel();
        tfEquipeB = new javax.swing.JTextField();
        btTerminar1 = new javax.swing.JButton();
        lbP1 = new javax.swing.JLabel();
        lbPontosB = new javax.swing.JLabel();
        btRmvB1 = new javax.swing.JButton();
        lbEquipeA = new javax.swing.JLabel();
        lbEquipeB = new javax.swing.JLabel();
        lbSet = new javax.swing.JLabel();
        btAddA1 = new javax.swing.JButton();
        LBP2 = new javax.swing.JLabel();
        btRmvA1 = new javax.swing.JButton();
        btAddB1 = new javax.swing.JButton();
        lbPontosA = new javax.swing.JLabel();
        lbPontosB2 = new javax.swing.JLabel();
        btRmvB2 = new javax.swing.JButton();
        LBP4 = new javax.swing.JLabel();
        btTerminar2 = new javax.swing.JButton();
        lbP3 = new javax.swing.JLabel();
        lbSet2 = new javax.swing.JLabel();
        lbEquipeA2 = new javax.swing.JLabel();
        lbPontosA2 = new javax.swing.JLabel();
        btAddA2 = new javax.swing.JButton();
        btRmvA2 = new javax.swing.JButton();
        lbEquipeB2 = new javax.swing.JLabel();
        btAddB2 = new javax.swing.JButton();
        lbP2 = new javax.swing.JLabel();
        lbPontosB1 = new javax.swing.JLabel();
        btRmvB4 = new javax.swing.JButton();
        lbEquipeA1 = new javax.swing.JLabel();
        lbEquipeB1 = new javax.swing.JLabel();
        lbSet4 = new javax.swing.JLabel();
        btAddA4 = new javax.swing.JButton();
        LBP3 = new javax.swing.JLabel();
        btRmvA4 = new javax.swing.JButton();
        btAddB4 = new javax.swing.JButton();
        btTerminar4 = new javax.swing.JButton();
        lbPontosA1 = new javax.swing.JLabel();
        lbP4 = new javax.swing.JLabel();
        lbPontosB3 = new javax.swing.JLabel();
        btRmvB5 = new javax.swing.JButton();
        lbEquipeA3 = new javax.swing.JLabel();
        lbEquipeB3 = new javax.swing.JLabel();
        lbSet5 = new javax.swing.JLabel();
        btAddA5 = new javax.swing.JButton();
        LBP5 = new javax.swing.JLabel();
        btRmvA5 = new javax.swing.JButton();
        btAddB5 = new javax.swing.JButton();
        btTerminar5 = new javax.swing.JButton();
        lbPontosA3 = new javax.swing.JLabel();
        lbP5 = new javax.swing.JLabel();
        lbPontosB4 = new javax.swing.JLabel();
        btRmvB3 = new javax.swing.JButton();
        lbEquipeA4 = new javax.swing.JLabel();
        lbEquipeB4 = new javax.swing.JLabel();
        lbSet3 = new javax.swing.JLabel();
        btAddA3 = new javax.swing.JButton();
        LBP6 = new javax.swing.JLabel();
        btRmvA3 = new javax.swing.JButton();
        btAddB3 = new javax.swing.JButton();
        btTerminar3 = new javax.swing.JButton();
        lbPontosA4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbSetsA = new javax.swing.JLabel();
        lbSetsB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btInicio.setText("Iniciar partida");
        btInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicioActionPerformed(evt);
            }
        });

        tfEquipeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEquipeAActionPerformed(evt);
            }
        });

        jLabel1.setText("Horário:");

        lbNomeA.setText("Equipe A:");

        tfHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHoraActionPerformed(evt);
            }
        });

        lbNomeB.setText("Equipe B:");

        tfEquipeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEquipeBActionPerformed(evt);
            }
        });

        btTerminar1.setText("Terminar set");
        btTerminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTerminar1ActionPerformed(evt);
            }
        });

        lbP1.setText("Pontuação");

        lbPontosB.setForeground(new java.awt.Color(0, 0, 255));
        lbPontosB.setText("pontosB");

        btRmvB1.setText("-");
        btRmvB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvB1ActionPerformed(evt);
            }
        });

        lbEquipeA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEquipeA.setForeground(new java.awt.Color(255, 0, 0));
        lbEquipeA.setText("EquipeA");

        lbEquipeB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEquipeB.setForeground(new java.awt.Color(0, 0, 255));
        lbEquipeB.setText("EquipeB");

        lbSet.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbSet.setText("Set 1");

        btAddA1.setText("+");
        btAddA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddA1ActionPerformed(evt);
            }
        });

        LBP2.setText("Pontuação");

        btRmvA1.setText("-");
        btRmvA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvA1ActionPerformed(evt);
            }
        });

        btAddB1.setText("+");
        btAddB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddB1ActionPerformed(evt);
            }
        });

        lbPontosA.setForeground(new java.awt.Color(255, 0, 0));
        lbPontosA.setText("pontosA");

        lbPontosB2.setForeground(new java.awt.Color(0, 0, 255));
        lbPontosB2.setText("pontosB");

        btRmvB2.setText("-");
        btRmvB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvB2ActionPerformed(evt);
            }
        });

        LBP4.setText("Pontuação");

        btTerminar2.setText("Terminar set");
        btTerminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTerminar2ActionPerformed(evt);
            }
        });

        lbP3.setText("Pontuação");

        lbSet2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbSet2.setText("Set 2");

        lbEquipeA2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEquipeA2.setForeground(new java.awt.Color(255, 0, 0));
        lbEquipeA2.setText("EquipeA");

        lbPontosA2.setForeground(new java.awt.Color(255, 0, 0));
        lbPontosA2.setText("pontosA");

        btAddA2.setText("+");
        btAddA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddA2ActionPerformed(evt);
            }
        });

        btRmvA2.setText("-");
        btRmvA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvA2ActionPerformed(evt);
            }
        });

        lbEquipeB2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEquipeB2.setForeground(new java.awt.Color(0, 0, 255));
        lbEquipeB2.setText("EquipeB");

        btAddB2.setText("+");
        btAddB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddB2ActionPerformed(evt);
            }
        });

        lbP2.setText("Pontuação");

        lbPontosB1.setForeground(new java.awt.Color(0, 0, 255));
        lbPontosB1.setText("pontosB");

        btRmvB4.setText("-");
        btRmvB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvB4ActionPerformed(evt);
            }
        });

        lbEquipeA1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEquipeA1.setForeground(new java.awt.Color(255, 0, 0));
        lbEquipeA1.setText("EquipeA");

        lbEquipeB1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEquipeB1.setForeground(new java.awt.Color(0, 0, 255));
        lbEquipeB1.setText("EquipeB");

        lbSet4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbSet4.setText("Set 4");

        btAddA4.setText("+");
        btAddA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddA4ActionPerformed(evt);
            }
        });

        LBP3.setText("Pontuação");

        btRmvA4.setText("-");
        btRmvA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvA4ActionPerformed(evt);
            }
        });

        btAddB4.setText("+");
        btAddB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddB4ActionPerformed(evt);
            }
        });

        btTerminar4.setText("Terminar set");
        btTerminar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTerminar4ActionPerformed(evt);
            }
        });

        lbPontosA1.setForeground(new java.awt.Color(255, 0, 0));
        lbPontosA1.setText("pontosA");

        lbP4.setText("Pontuação");

        lbPontosB3.setForeground(new java.awt.Color(0, 0, 255));
        lbPontosB3.setText("pontosB");

        btRmvB5.setText("-");
        btRmvB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvB5ActionPerformed(evt);
            }
        });

        lbEquipeA3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEquipeA3.setForeground(new java.awt.Color(255, 0, 0));
        lbEquipeA3.setText("EquipeA");

        lbEquipeB3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEquipeB3.setForeground(new java.awt.Color(0, 0, 255));
        lbEquipeB3.setText("EquipeB");

        lbSet5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbSet5.setText("Set 5");

        btAddA5.setText("+");
        btAddA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddA5ActionPerformed(evt);
            }
        });

        LBP5.setText("Pontuação");

        btRmvA5.setText("-");
        btRmvA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvA5ActionPerformed(evt);
            }
        });

        btAddB5.setText("+");
        btAddB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddB5ActionPerformed(evt);
            }
        });

        btTerminar5.setText("Terminar set");
        btTerminar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTerminar5ActionPerformed(evt);
            }
        });

        lbPontosA3.setForeground(new java.awt.Color(255, 0, 0));
        lbPontosA3.setText("pontosA");

        lbP5.setText("Pontuação");

        lbPontosB4.setForeground(new java.awt.Color(0, 0, 255));
        lbPontosB4.setText("pontosB");

        btRmvB3.setText("-");
        btRmvB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvB3ActionPerformed(evt);
            }
        });

        lbEquipeA4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEquipeA4.setForeground(new java.awt.Color(255, 0, 0));
        lbEquipeA4.setText("EquipeA");

        lbEquipeB4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbEquipeB4.setForeground(new java.awt.Color(0, 0, 255));
        lbEquipeB4.setText("EquipeB");

        lbSet3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbSet3.setText("Set 3");

        btAddA3.setText("+");
        btAddA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddA3ActionPerformed(evt);
            }
        });

        LBP6.setText("Pontuação");

        btRmvA3.setText("-");
        btRmvA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRmvA3ActionPerformed(evt);
            }
        });

        btAddB3.setText("+");
        btAddB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddB3ActionPerformed(evt);
            }
        });

        btTerminar3.setText("Terminar set");
        btTerminar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTerminar3ActionPerformed(evt);
            }
        });

        lbPontosA4.setForeground(new java.awt.Color(255, 0, 0));
        lbPontosA4.setText("pontosA");

        jLabel4.setText("Sets");

        lbSetsA.setText("00");

        lbSetsB.setText("00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAddA3)
                            .addComponent(btRmvA3)
                            .addComponent(btAddB3)
                            .addComponent(btRmvB3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSet3)
                                .addGap(47, 47, 47)
                                .addComponent(btTerminar3))
                            .addComponent(lbEquipeA2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LBP4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbPontosB2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbP3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbPontosA2)))
                            .addComponent(lbEquipeB2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfHora, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbSetsA)
                                            .addComponent(lbSetsB))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbNomeB)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfEquipeB))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbNomeA)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfEquipeA, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAddA2)
                                    .addComponent(btRmvA2)
                                    .addComponent(btAddB2)
                                    .addComponent(btRmvB2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbSet2)
                                        .addGap(18, 18, 18)
                                        .addComponent(btTerminar2))
                                    .addComponent(lbEquipeA1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LBP3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbPontosB1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbP2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbPontosA1)))
                                    .addComponent(lbEquipeB1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAddA4)
                                    .addComponent(btRmvA4)
                                    .addComponent(btAddB4)
                                    .addComponent(btRmvB4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbSet4)
                                        .addGap(47, 47, 47)
                                        .addComponent(btTerminar4))
                                    .addComponent(lbEquipeA3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LBP5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbPontosB3))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbP4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbPontosA3)))
                                    .addComponent(lbEquipeB3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAddA5)
                                    .addComponent(btRmvA5)
                                    .addComponent(btAddB5)
                                    .addComponent(btRmvB5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(btTerminar5))
                                    .addComponent(lbSet5)
                                    .addComponent(lbEquipeA4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LBP6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbPontosB4))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbP5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbPontosA4)))
                                    .addComponent(lbEquipeB4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btAddA1)
                                    .addComponent(btRmvA1)
                                    .addComponent(btAddB1)
                                    .addComponent(btRmvB1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbSet)
                                            .addComponent(lbEquipeA)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(LBP2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lbPontosB))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lbP1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lbPontosA))))
                                        .addGap(18, 18, 18)
                                        .addComponent(btTerminar1))
                                    .addComponent(lbEquipeB))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSetsA)
                    .addComponent(lbNomeA)
                    .addComponent(tfEquipeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInicio)
                    .addComponent(lbNomeB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEquipeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSetsB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btAddA1)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btRmvA1)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btAddB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRmvB1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSet)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btTerminar1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEquipeA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPontosA)
                            .addComponent(lbP1))
                        .addGap(18, 18, 18)
                        .addComponent(lbEquipeB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPontosB)
                            .addComponent(LBP2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btAddA2)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btRmvA2)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btAddB2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRmvB2))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSet2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btTerminar2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbEquipeA1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPontosA1)
                            .addComponent(lbP2))
                        .addGap(18, 18, 18)
                        .addComponent(lbEquipeB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPontosB1)
                            .addComponent(LBP3))
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSet3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btTerminar3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAddA3)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btRmvA3)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btAddB3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRmvB3))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEquipeA2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPontosA2)
                            .addComponent(lbP3))
                        .addGap(18, 18, 18)
                        .addComponent(lbEquipeB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPontosB2)
                            .addComponent(LBP4))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSet4)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btTerminar4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAddA4)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btRmvA4)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btAddB4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRmvB4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbEquipeA3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPontosA3)
                            .addComponent(lbP4))
                        .addGap(18, 18, 18)
                        .addComponent(lbEquipeB3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPontosB3)
                            .addComponent(LBP5))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSet5)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btTerminar5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEquipeA4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPontosA4)
                            .addComponent(lbP5))
                        .addGap(18, 18, 18)
                        .addComponent(lbEquipeB4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPontosB4)
                            .addComponent(LBP6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAddA5)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btRmvA5)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btAddB5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRmvB5)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEquipeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEquipeAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEquipeAActionPerformed

    private void tfHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHoraActionPerformed

    private void tfEquipeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEquipeBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEquipeBActionPerformed

    private void btInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicioActionPerformed
        if (!tfEquipeA.getText().equals("") && !tfEquipeB.getText().equals("") && !tfHora.getText().equals("")) {
            a = new Equipe(tfEquipeA.getText());
            b = new Equipe(tfEquipeB.getText());
            partida = new Partida(a, b, tfHora.getText());
            tfEquipeA.setEditable(false);
            tfEquipeB.setEditable(false);
            tfHora.setEditable(false);

            lbEquipeA.setText(a.getNome());
            lbEquipeB.setText(b.getNome());
            lbPontosA.setText(a.getPontuacaoString());
            lbPontosB.setText(b.getPontuacaoString());

            addBotao(btAddA1, btAddB1, btRmvA1, btRmvB1);
        }
    }//GEN-LAST:event_btInicioActionPerformed

    private void btTerminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTerminar1ActionPerformed
        tiraBotao(btAddA1, btAddB1, btRmvA1, btRmvB1, btTerminar1);
        addBotao(btAddA2, btAddB2, btRmvA2, btRmvB2);
        partida.terminaSet();
        lbSetsA.setText(a.getSetsVencidosstring());
        lbSetsB.setText(b.getSetsVencidosstring());
        a.setPontuacao(0);
        b.setPontuacao(0);
        lbEquipeA1.setText(a.getNome());
        lbEquipeB1.setText(b.getNome());
        lbPontosA1.setText(a.getPontuacaoString());
        lbPontosB1.setText(b.getPontuacaoString());
    }//GEN-LAST:event_btTerminar1ActionPerformed

    private void btRmvA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvA1ActionPerformed
        a.tiraPonto();
        lbPontosA.setText(a.getPontuacaoString());
        if (fimSet())
            btTerminar1.setVisible(true);
        else
            btTerminar1.setVisible(false);
    }//GEN-LAST:event_btRmvA1ActionPerformed

    private void btAddB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddB1ActionPerformed
        b.ganhaPonto();
        lbPontosB.setText(b.getPontuacaoString());
        if (fimSet())
            btTerminar1.setVisible(true);
        else
            btTerminar1.setVisible(false);
    }//GEN-LAST:event_btAddB1ActionPerformed

    private void btAddA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddA1ActionPerformed
        a.ganhaPonto();
        lbPontosA.setText(a.getPontuacaoString());
        if (fimSet()) {
            btTerminar1.setVisible(true);
        } else {
            btTerminar1.setVisible(false);
        }
    }//GEN-LAST:event_btAddA1ActionPerformed

    private void btRmvB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvB1ActionPerformed
        b.tiraPonto();
        lbPontosB.setText(b.getPontuacaoString());
        if (fimSet())
            btTerminar1.setVisible(true);
        else
            btTerminar1.setVisible(false);
    }//GEN-LAST:event_btRmvB1ActionPerformed

    private void btAddB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddB2ActionPerformed
        b.ganhaPonto();
        lbPontosB1.setText(b.getPontuacaoString());
        if (fimSet())
            btTerminar2.setVisible(true);
        else
            btTerminar2.setVisible(false);
    }//GEN-LAST:event_btAddB2ActionPerformed

    private void btRmvA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvA2ActionPerformed
        a.tiraPonto();
        lbPontosA1.setText(a.getPontuacaoString());
        if (fimSet())
            btTerminar2.setVisible(true);
        else
            btTerminar2.setVisible(false);
    }//GEN-LAST:event_btRmvA2ActionPerformed

    private void btAddA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddA2ActionPerformed
        a.ganhaPonto();
        lbPontosA1.setText(a.getPontuacaoString());
        if (fimSet()) {
            btTerminar2.setVisible(true);
        } else {
            btTerminar2.setVisible(false);
        }
    }//GEN-LAST:event_btAddA2ActionPerformed

    private void btTerminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTerminar2ActionPerformed
        tiraBotao(btAddA2, btAddB2, btRmvA2, btRmvB2, btTerminar2);
        addBotao(btAddA3, btAddB3, btRmvA3, btRmvB3);
        partida.terminaSet();
        lbSetsA.setText(a.getSetsVencidosstring());
        lbSetsB.setText(b.getSetsVencidosstring());
        a.setPontuacao(0);
        b.setPontuacao(0);
        lbEquipeA2.setText(a.getNome());
        lbEquipeB2.setText(b.getNome());
        lbPontosA2.setText(a.getPontuacaoString());
        lbPontosB2.setText(b.getPontuacaoString());
    }//GEN-LAST:event_btTerminar2ActionPerformed

    private void btRmvB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvB2ActionPerformed
        b.tiraPonto();
        lbPontosB1.setText(b.getPontuacaoString());
        if (fimSet())
            btTerminar2.setVisible(true);
        else
            btTerminar2.setVisible(false);
    }//GEN-LAST:event_btRmvB2ActionPerformed

    private void btRmvB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvB4ActionPerformed
        b.tiraPonto();
        lbPontosB3.setText(b.getPontuacaoString());
        if (fimSet())
            btTerminar4.setVisible(true);
        else
            btTerminar4.setVisible(false);
    }//GEN-LAST:event_btRmvB4ActionPerformed

    private void btAddA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddA4ActionPerformed
        a.ganhaPonto();
        lbPontosA3.setText(a.getPontuacaoString());
        if (fimSet()) {
            btTerminar4.setVisible(true);
        } else {
            btTerminar4.setVisible(false);
        }
    }//GEN-LAST:event_btAddA4ActionPerformed

    private void btRmvA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvA4ActionPerformed
        a.tiraPonto();
        lbPontosA3.setText(a.getPontuacaoString());
        if (fimSet())
            btTerminar4.setVisible(true);
        else
            btTerminar4.setVisible(false);
    }//GEN-LAST:event_btRmvA4ActionPerformed

    private void btAddB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddB4ActionPerformed
        b.ganhaPonto();
        lbPontosB3.setText(b.getPontuacaoString());
        if (fimSet())
            btTerminar4.setVisible(true);
        else
            btTerminar4.setVisible(false);
    }//GEN-LAST:event_btAddB4ActionPerformed

    private void btTerminar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTerminar4ActionPerformed
        tiraBotao(btAddA4, btAddB4, btRmvA4, btRmvB4, btTerminar4);
        partida.terminaSet();
        if (a.getSetsVencidos() > 2) {
            lbNomeA.setText("Vencedores");
            lbNomeA.setForeground(Color.GREEN);
        } else if (b.getSetsVencidos() > 2) {
            lbNomeB.setText("Vencedores");
            lbNomeB.setForeground(Color.GREEN);
        } else {
            addBotao(btAddA5, btAddB5, btRmvA5, btRmvB5);
            a.setPontuacao(0);
            b.setPontuacao(0);
            lbEquipeA4.setText(a.getNome());
            lbEquipeB4.setText(b.getNome());
            lbPontosA4.setText(a.getPontuacaoString());
            lbPontosB4.setText(b.getPontuacaoString());
        }
    }//GEN-LAST:event_btTerminar4ActionPerformed

    private void btRmvB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvB5ActionPerformed
        b.tiraPonto();
        lbPontosB4.setText(b.getPontuacaoString());
        if (fimSetFinal())
            btTerminar5.setVisible(true);
        else
            btTerminar5.setVisible(false);
    }//GEN-LAST:event_btRmvB5ActionPerformed

    private void btAddA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddA5ActionPerformed
        a.ganhaPonto();
        lbPontosA4.setText(a.getPontuacaoString());
        if (fimSetFinal()) {
            btTerminar5.setVisible(true);
        } else {
            btTerminar5.setVisible(false);
        }
    }//GEN-LAST:event_btAddA5ActionPerformed

    private void btRmvA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvA5ActionPerformed
        a.tiraPonto();
        lbPontosA4.setText(a.getPontuacaoString());
        if (fimSetFinal())
            btTerminar5.setVisible(true);
        else
            btTerminar5.setVisible(false);
    }//GEN-LAST:event_btRmvA5ActionPerformed

    private void btAddB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddB5ActionPerformed
        b.ganhaPonto();
        lbPontosB4.setText(b.getPontuacaoString());
        if (fimSetFinal())
            btTerminar5.setVisible(true);
        else
            btTerminar5.setVisible(false);
    }//GEN-LAST:event_btAddB5ActionPerformed

    private void btTerminar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTerminar5ActionPerformed
        tiraBotao(btAddA5, btAddB5, btRmvA5, btRmvB5, btTerminar5);
        partida.terminaSet();
        a.setPontuacao(0);
        b.setPontuacao(0);
        if (a.getSetsVencidos() > 2) {
            lbNomeA.setText("Vencedores");
            lbNomeA.setForeground(Color.GREEN);
        }else if(b.getSetsVencidos() > 2){
            lbNomeB.setText("Vencedores");
            lbNomeB.setForeground(Color.GREEN);
        }
    }//GEN-LAST:event_btTerminar5ActionPerformed

    private void btRmvB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvB3ActionPerformed
        b.tiraPonto();
        lbPontosB2.setText(b.getPontuacaoString());
        if (fimSet())
            btTerminar3.setVisible(true);
        else
            btTerminar3.setVisible(false);
    }//GEN-LAST:event_btRmvB3ActionPerformed

    private void btAddA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddA3ActionPerformed
        a.ganhaPonto();
        lbPontosA2.setText(a.getPontuacaoString());
        if (fimSet()) {
            btTerminar3.setVisible(true);
        } else {
            btTerminar3.setVisible(false);
        }
    }//GEN-LAST:event_btAddA3ActionPerformed

    private void btRmvA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRmvA3ActionPerformed
        a.tiraPonto();
        lbPontosA2.setText(a.getPontuacaoString());
        if (fimSet())
            btTerminar3.setVisible(true);
        else
            btTerminar3.setVisible(false);
    }//GEN-LAST:event_btRmvA3ActionPerformed

    private void btAddB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddB3ActionPerformed
        b.ganhaPonto();
        lbPontosB2.setText(b.getPontuacaoString());
        if (fimSet())
            btTerminar3.setVisible(true);
        else
            btTerminar3.setVisible(false);
    }//GEN-LAST:event_btAddB3ActionPerformed

    private void btTerminar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTerminar3ActionPerformed
        tiraBotao(btAddA3, btAddB3, btRmvA3, btRmvB3, btTerminar3);
        partida.terminaSet();
        lbSetsA.setText(a.getSetsVencidosstring());
        lbSetsB.setText(b.getSetsVencidosstring());
        if (a.getSetsVencidos() > 2) {
            lbNomeA.setText("Vencedores");
            lbNomeA.setForeground(Color.GREEN);
        } else if (b.getSetsVencidos() > 2) {
            lbNomeB.setText("Vencedores");
            lbNomeB.setForeground(Color.GREEN);
        } else {
            addBotao(btAddA4, btAddB4, btRmvA4, btRmvB4);
            a.setPontuacao(0);
            b.setPontuacao(0);
            lbEquipeA3.setText(a.getNome());
            lbEquipeB3.setText(b.getNome());
            lbPontosA3.setText(a.getPontuacaoString());
            lbPontosB3.setText(b.getPontuacaoString());
        }
    }//GEN-LAST:event_btTerminar3ActionPerformed

    private void tiraBotao(JButton b1, JButton b2, JButton b3, JButton b4, JButton b5) {
        b1.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        b5.setVisible(false);
    }

    private void addBotao(JButton b1, JButton b2, JButton b3, JButton b4) {
        b1.setVisible(true);
        b2.setVisible(true);
        b3.setVisible(true);
        b4.setVisible(true);
    }

    private boolean fimSet() {
        if (a.getPontuacao() >= 25 || b.getPontuacao() >= 25) {
            int diferenca = a.getPontuacao() - b.getPontuacao();
            if (diferenca >= 2) {
                return true;
            }if (diferenca <= -2){
                return true;
            }
        }
        return false;
    }

    private boolean fimSetFinal() {
        if (a.getPontuacao() >= 15 || b.getPontuacao() >= 15) {
            int diferenca = a.getPontuacao() - b.getPontuacao();
            diferenca = (diferenca * diferenca) / diferenca;
            if (diferenca >= 2) {
                return true;
            }
        }
        return false;
    }

    private void removePonto(Equipe e) {

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBP2;
    private javax.swing.JLabel LBP3;
    private javax.swing.JLabel LBP4;
    private javax.swing.JLabel LBP5;
    private javax.swing.JLabel LBP6;
    private javax.swing.JButton btAddA1;
    private javax.swing.JButton btAddA2;
    private javax.swing.JButton btAddA3;
    private javax.swing.JButton btAddA4;
    private javax.swing.JButton btAddA5;
    private javax.swing.JButton btAddB1;
    private javax.swing.JButton btAddB2;
    private javax.swing.JButton btAddB3;
    private javax.swing.JButton btAddB4;
    private javax.swing.JButton btAddB5;
    private javax.swing.JButton btInicio;
    private javax.swing.JButton btRmvA1;
    private javax.swing.JButton btRmvA2;
    private javax.swing.JButton btRmvA3;
    private javax.swing.JButton btRmvA4;
    private javax.swing.JButton btRmvA5;
    private javax.swing.JButton btRmvB1;
    private javax.swing.JButton btRmvB2;
    private javax.swing.JButton btRmvB3;
    private javax.swing.JButton btRmvB4;
    private javax.swing.JButton btRmvB5;
    private javax.swing.JButton btTerminar1;
    private javax.swing.JButton btTerminar2;
    private javax.swing.JButton btTerminar3;
    private javax.swing.JButton btTerminar4;
    private javax.swing.JButton btTerminar5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbEquipeA;
    private javax.swing.JLabel lbEquipeA1;
    private javax.swing.JLabel lbEquipeA2;
    private javax.swing.JLabel lbEquipeA3;
    private javax.swing.JLabel lbEquipeA4;
    private javax.swing.JLabel lbEquipeB;
    private javax.swing.JLabel lbEquipeB1;
    private javax.swing.JLabel lbEquipeB2;
    private javax.swing.JLabel lbEquipeB3;
    private javax.swing.JLabel lbEquipeB4;
    private javax.swing.JLabel lbNomeA;
    private javax.swing.JLabel lbNomeB;
    private javax.swing.JLabel lbP1;
    private javax.swing.JLabel lbP2;
    private javax.swing.JLabel lbP3;
    private javax.swing.JLabel lbP4;
    private javax.swing.JLabel lbP5;
    private javax.swing.JLabel lbPontosA;
    private javax.swing.JLabel lbPontosA1;
    private javax.swing.JLabel lbPontosA2;
    private javax.swing.JLabel lbPontosA3;
    private javax.swing.JLabel lbPontosA4;
    private javax.swing.JLabel lbPontosB;
    private javax.swing.JLabel lbPontosB1;
    private javax.swing.JLabel lbPontosB2;
    private javax.swing.JLabel lbPontosB3;
    private javax.swing.JLabel lbPontosB4;
    private javax.swing.JLabel lbSet;
    private javax.swing.JLabel lbSet2;
    private javax.swing.JLabel lbSet3;
    private javax.swing.JLabel lbSet4;
    private javax.swing.JLabel lbSet5;
    private javax.swing.JLabel lbSetsA;
    private javax.swing.JLabel lbSetsB;
    private javax.swing.JTextField tfEquipeA;
    private javax.swing.JTextField tfEquipeB;
    private javax.swing.JTextField tfHora;
    // End of variables declaration//GEN-END:variables
}
